services:
  site-monitor:
    image: pandects/site-monitor:latest
    container_name: site-monitor
    environment:
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}
      FIREBASE_MEASUREMENT_ID: ${FIREBASE_MEASUREMENT_ID}
      FIREBASE_SERVICE_ACCOUNT_LOCATION: ${FIREBASE_SERVICE_ACCOUNT_LOCATION}
      SQLITE_DB_LOCATION: ${SQLITE_DB_LOCATION}
    volumes:
      - ./db:/db
      - ./conf:/conf
    ports:
      - 3000:3000
    restart: unless-stopped